#!/bin/bash

path=`pwd`

# 创建数据库
python dbinit.py

# 编译dht11
echo -e '\e[1;32m --===[ Compile dht ]===-- \e[0m'
gcc dht11.c gpio.c -std=gnu99 -o dht11

# 创建定时任务
echo -e '\e[1;32m --===[ Create Job ]===-- \e[0m'

crontab -l | { cat; echo "0 * * * * ${path}/job.sh"; } | crontab -

# 启动web服务
echo -e '\e[1;32m --===[ Config web.py ]===-- \e[0m'
ln -s `pwd`/webpy/web .

echo -e '\e[1;32m --===[ Start Server ]===-- \e[0m'
python server.py > log.txt 2>&1 &

echo -e '\e[1;32m --===[ Work Done! ]===-- \e[0m'
echo 'Open http://localhost:8080/status check sever status'
